export const seedData = {
  employees: [
    {
      id: "550e8400-e29b-41d4-a716-446655440000",
      first_name: "John",
      last_name: "Doe",
      email: "john.doe@example.com",
      phone: "555-123-4567",
      position: "Software Engineer",
      department: "Engineering",
      hire_date: "2022-01-15",
      status: "active",
      manager_id: null,
      avatar_url: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "550e8400-e29b-41d4-a716-446655440001",
      first_name: "Jane",
      last_name: "Smith",
      email: "jane.smith@example.com",
      phone: "555-987-6543",
      position: "Product Manager",
      department: "Product",
      hire_date: "2021-06-10",
      status: "active",
      manager_id: "550e8400-e29b-41d4-a716-446655440000",
      avatar_url: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "550e8400-e29b-41d4-a716-446655440002",
      first_name: "Michael",
      last_name: "Johnson",
      email: "michael.johnson@example.com",
      phone: "555-456-7890",
      position: "UX Designer",
      department: "Design",
      hire_date: "2022-03-22",
      status: "active",
      manager_id: "550e8400-e29b-41d4-a716-446655440001",
      avatar_url: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "550e8400-e29b-41d4-a716-446655440003",
      first_name: "Emily",
      last_name: "Williams",
      email: "emily.williams@example.com",
      phone: "555-789-0123",
      position: "Marketing Specialist",
      department: "Marketing",
      hire_date: "2021-11-05",
      status: "active",
      manager_id: "550e8400-e29b-41d4-a716-446655440000",
      avatar_url: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "550e8400-e29b-41d4-a716-446655440004",
      first_name: "David",
      last_name: "Brown",
      email: "david.brown@example.com",
      phone: "555-234-5678",
      position: "Sales Representative",
      department: "Sales",
      hire_date: "2022-02-18",
      status: "active",
      manager_id: "550e8400-e29b-41d4-a716-446655440001",
      avatar_url: "/placeholder.svg?height=40&width=40",
    },
  ],
  job_postings: [
    {
      title: "Senior Software Engineer",
      description: "We are looking for an experienced software engineer to join our team.",
      department: "Engineering",
      location: "San Francisco, CA",
      salary_range: { min: 120000, max: 150000 },
      required_skills: ["JavaScript", "React", "Node.js", "AWS"],
      status: "open",
    },
    {
      title: "Product Manager",
      description: "Join our product team to help shape the future of our platform.",
      department: "Product",
      location: "New York, NY",
      salary_range: { min: 110000, max: 140000 },
      required_skills: ["Product Management", "Agile", "User Research"],
      status: "open",
    },
    {
      title: "UX/UI Designer",
      description: "Help us create beautiful and intuitive user experiences.",
      department: "Design",
      location: "Remote",
      salary_range: { min: 90000, max: 120000 },
      required_skills: ["Figma", "UI Design", "User Research"],
      status: "closed",
    },
  ],
  candidates: [
    {
      job_posting_id: null, // Will be set during seeding
      first_name: "Alex",
      last_name: "Johnson",
      email: "alex.johnson@example.com",
      phone: "555-111-2222",
      resume_url: "/placeholder.svg?height=40&width=40",
      skills: ["JavaScript", "React", "Node.js"],
      experience_years: 5,
      status: "screening",
      ai_score: 85,
    },
    {
      job_posting_id: null, // Will be set during seeding
      first_name: "Sarah",
      last_name: "Miller",
      email: "sarah.miller@example.com",
      phone: "555-333-4444",
      resume_url: "/placeholder.svg?height=40&width=40",
      skills: ["Product Management", "Agile", "Jira"],
      experience_years: 7,
      status: "interview",
      ai_score: 92,
    },
    {
      job_posting_id: null, // Will be set during seeding
      first_name: "Chris",
      last_name: "Taylor",
      email: "chris.taylor@example.com",
      phone: "555-555-6666",
      resume_url: "/placeholder.svg?height=40&width=40",
      skills: ["Figma", "UI Design", "Sketch"],
      experience_years: 4,
      status: "applied",
      ai_score: 78,
    },
  ],
  onboarding_tasks: [
    {
      title: "Complete HR paperwork",
      description: "Fill out all required HR forms and documents",
      department: "All",
      estimated_days: 1,
      is_required: true,
    },
    {
      title: "IT setup",
      description: "Set up computer, email, and access to necessary systems",
      department: "All",
      estimated_days: 2,
      is_required: true,
    },
    {
      title: "Team introduction",
      description: "Meet with team members and get to know the team",
      department: "All",
      estimated_days: 1,
      is_required: true,
    },
    {
      title: "Training session",
      description: "Attend training session for company policies and procedures",
      department: "All",
      estimated_days: 3,
      is_required: true,
    },
  ],
  benefits: [
    {
      name: "Health Insurance",
      description: "Comprehensive health insurance coverage",
      cost: 500.0,
      is_active: true,
    },
    {
      name: "Dental Insurance",
      description: "Dental insurance coverage",
      cost: 100.0,
      is_active: true,
    },
    {
      name: "401(k) Plan",
      description: "Retirement savings plan with company matching",
      cost: 0.0,
      is_active: true,
    },
    {
      name: "Gym Membership",
      description: "Monthly gym membership reimbursement",
      cost: 50.0,
      is_active: true,
    },
  ],
  compliance_policies: [
    {
      title: "Code of Conduct",
      description: "Guidelines for professional behavior in the workplace",
      document_url: "/placeholder.svg?height=40&width=40",
      region: "Global",
      is_active: true,
    },
    {
      title: "Data Privacy Policy",
      description: "Guidelines for handling sensitive data",
      document_url: "/placeholder.svg?height=40&width=40",
      region: "Global",
      is_active: true,
    },
    {
      title: "GDPR Compliance",
      description: "Guidelines for compliance with GDPR regulations",
      document_url: "/placeholder.svg?height=40&width=40",
      region: "Europe",
      is_active: true,
    },
  ],
  integrations: [
    {
      name: "SAP HR",
      provider: "SAP",
      api_key: "sample_api_key_1",
      config: { endpoint: "https://api.sap.example.com", version: "v1" },
      status: "active",
    },
    {
      name: "Oracle HCM",
      provider: "Oracle",
      api_key: "sample_api_key_2",
      config: { endpoint: "https://api.oracle.example.com", version: "v2" },
      status: "inactive",
    },
    {
      name: "Workday",
      provider: "Workday",
      api_key: "sample_api_key_3",
      config: { endpoint: "https://api.workday.example.com", version: "v1" },
      status: "active",
    },
  ],
  chatbot_faqs: [
    {
      question: "How do I request time off?",
      answer:
        "You can request time off by navigating to the Time Off section in the dashboard and clicking on 'Request Time Off'.",
      category: "Time Off",
      is_active: true,
    },
    {
      question: "How do I update my personal information?",
      answer:
        "You can update your personal information by going to your profile settings and clicking on 'Edit Profile'.",
      category: "Profile",
      is_active: true,
    },
    {
      question: "When is the next payday?",
      answer:
        "Paydays are on the 15th and last day of each month. If these days fall on a weekend or holiday, payment will be made on the preceding business day.",
      category: "Payroll",
      is_active: true,
    },
  ],
}

