"use client"

import type React from "react"

import { useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { Eye, EyeOff, Mail, Lock, User, ArrowRight } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { supabase } from "@/lib/supabase"
import { toast } from "@/components/ui/use-toast"

export default function RegisterPage() {
  const [name, setName] = useState("")
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [confirmPassword, setConfirmPassword] = useState("")
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const router = useRouter()

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)

    if (password !== confirmPassword) {
      setError("Passwords do not match")
      toast({
        title: "Password Error",
        description: "The passwords you entered do not match.",
        variant: "destructive"
      })
      return
    }

    if (password.length < 6) {
      setError("Password must be at least 6 characters long")
      toast({
        title: "Password Error",
        description: "Please use a password that is at least 6 characters long.",
        variant: "destructive"
      })
      return
    }

    setIsLoading(true)

    try {
      // Sign up with Supabase auth
      const { data, error: signUpError } = await supabase.auth.signUp({
        email,
        password,
        options: {
          data: {
            full_name: name,
          },
          emailRedirectTo: `${window.location.origin}/auth/callback`,
        },
      })

      if (signUpError) throw signUpError

      // Create user profile
      if (data?.user) {
        console.log("[handleRegister] Attempting to create profile for user:", data.user.id);
        try {
          // Insert into tenant_users table (trigger handles tenant_id generation)
          const { error: profileInsertError } = await supabase
            .from('tenant_users')
            .insert({
              user_id: data.user.id,
              email: email,
              full_name: name,
              role: 'user'
            })
            .single(); // Use single() to get the inserted row if possible, or select later

          if (profileInsertError) {
            console.error("[handleRegister] Error inserting profile:", profileInsertError);
            // More specific error message for the user
            throw new Error("Failed to create user profile. Database insertion failed.");
          }

          console.log("[handleRegister] Profile inserted successfully.");

          // Fetch the created profile to get the tenant_id generated by the trigger
          const { data: profileData, error: profileFetchError } = await supabase
            .from('tenant_users')
            .select('tenant_id')
            .eq('user_id', data.user.id)
            .single();

          if (profileFetchError || !profileData?.tenant_id) {
               console.error("[handleRegister] Error fetching created profile or tenant_id:", profileFetchError || "Tenant ID not found in fetched profile");
               // This is a critical error, but we'll proceed to avoid blocking registration
               // Consider adding monitoring for this scenario
                toast({
                    title: "Warning: Tenant ID Missing",
                    description: "Your account was created, but we couldn't retrieve your tenant information. Some features may not work correctly.",
                    variant: "destructive"
                });
          }

          // Update user metadata with the tenant_id
          if(profileData?.tenant_id) {
             const { error: metadataError } = await supabase.auth.updateUser({
                 data: { tenant_id: profileData.tenant_id }
             });
             
             if (metadataError) {
                 console.error("Error updating user metadata with tenant_id:", metadataError);
                 // Log this error, but don't block the user
             }
          }

          toast({
            title: "Registration Successful",
            description: "Please check your email to confirm your account.",
          })
          
          router.push("/login")
        } catch (profileErr: any) {
          console.error("Profile creation error:", profileErr)
          // We can't delete the user from the client side, so we'll just notify
          toast({
            title: "Profile Creation Failed",
            description: "Your account was created but we couldn't set up your profile. Please contact support.",
            variant: "destructive"
          })
          throw new Error("Failed to set up your account profile.")
        }
      }
    } catch (err: any) {
      console.error("Registration error:", err)
      setError(err.message || "Failed to create account. Please try again.")
      toast({
        title: "Registration Failed",
        description: err.message || "There was a problem creating your account.",
        variant: "destructive"
      })
    } finally {
      setIsLoading(false)
    }
  }

  const handleGoogleSignIn = async () => {
    setIsLoading(true)
    setError(null)
    
    try {
      const { error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
          redirectTo: `${window.location.origin}/auth/callback`
        }
      })
      
      if (error) throw error
    } catch (err: any) {
      console.error("Google sign-in error:", err)
      setError(err.message || "Failed to sign in with Google.")
      toast({
        title: "Google Login Failed",
        description: err.message || "Could not authenticate with Google.",
        variant: "destructive"
      })
      setIsLoading(false)
    }
  }

  const handleMicrosoftSignIn = async () => {
    setIsLoading(true)
    setError(null)
    
    try {
      const { error } = await supabase.auth.signInWithOAuth({
        provider: 'azure',
        options: {
          redirectTo: `${window.location.origin}/auth/callback`
        }
      })
      
      if (error) throw error
    } catch (err: any) {
      console.error("Microsoft sign-in error:", err)
      setError(err.message || "Failed to sign in with Microsoft.")
      toast({
        title: "Microsoft Login Failed",
        description: err.message || "Could not authenticate with Microsoft.",
        variant: "destructive"
      })
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-background to-secondary/30 p-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold tracking-tight">HR Suite</h1>
          <p className="text-muted-foreground mt-2">AI-Powered HR Management</p>
        </div>

        <Card className="border-border/40 shadow-lg">
          <CardHeader>
            <CardTitle>Create an Account</CardTitle>
            <CardDescription>Enter your details to create a new account</CardDescription>
          </CardHeader>
          <CardContent>
            {error && (
              <div className="mb-4 p-3 text-sm bg-destructive/10 text-destructive rounded-md">
                {error}
              </div>
            )}
            <form onSubmit={handleRegister} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="name">Full Name</Label>
                <div className="relative">
                  <User className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                  <Input
                    id="name"
                    type="text"
                    placeholder="John Doe"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    className="pl-10"
                    required
                    disabled={isLoading}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <div className="relative">
                  <Mail className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                  <Input
                    id="email"
                    type="email"
                    placeholder="name@company.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="pl-10"
                    required
                    disabled={isLoading}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <div className="relative">
                  <Lock className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                  <Input
                    id="password"
                    type={showPassword ? "text" : "password"}
                    placeholder="••••••••"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="pl-10"
                    required
                    disabled={isLoading}
                    minLength={6}
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                    onClick={() => setShowPassword(!showPassword)}
                    disabled={isLoading}
                  >
                    {showPassword ? (
                      <EyeOff className="h-4 w-4 text-muted-foreground" />
                    ) : (
                      <Eye className="h-4 w-4 text-muted-foreground" />
                    )}
                    <span className="sr-only">{showPassword ? "Hide password" : "Show password"}</span>
                  </Button>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="confirmPassword">Confirm Password</Label>
                <div className="relative">
                  <Lock className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                  <Input
                    id="confirmPassword"
                    type={showConfirmPassword ? "text" : "password"}
                    placeholder="••••••••"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    className="pl-10"
                    required
                    disabled={isLoading}
                    minLength={6}
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    disabled={isLoading}
                  >
                    {showConfirmPassword ? (
                      <EyeOff className="h-4 w-4 text-muted-foreground" />
                    ) : (
                      <Eye className="h-4 w-4 text-muted-foreground" />
                    )}
                    <span className="sr-only">{showConfirmPassword ? "Hide password" : "Show password"}</span>
                  </Button>
                </div>
              </div>

              <Button
                type="submit"
                className="w-full group transition-all duration-300 hover:translate-y-[-2px]"
                disabled={isLoading}
              >
                {isLoading ? "Creating account..." : "Create Account"}
                <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
              </Button>
            </form>

            <div className="mt-6">
              <div className="relative">
                <div className="absolute inset-0 flex items-center">
                  <Separator />
                </div>
                <div className="relative flex justify-center text-xs uppercase">
                  <span className="bg-card px-2 text-muted-foreground">Or continue with</span>
                </div>
              </div>

              <div className="mt-4 grid grid-cols-2 gap-3">
                <Button
                  variant="outline"
                  className="transition-all duration-300 hover:bg-blue-50 dark:hover:bg-blue-950"
                  onClick={handleGoogleSignIn}
                  disabled={isLoading}
                  type="button"
                >
                  <svg className="mr-2 h-4 w-4" viewBox="0 0 24 24">
                    <path
                      d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                      fill="#4285F4"
                    />
                    <path
                      d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                      fill="#34A853"
                    />
                    <path
                      d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                      fill="#FBBC05"
                    />
                    <path
                      d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                      fill="#EA4335"
                    />
                  </svg>
                  Google
                </Button>
                <Button
                  variant="outline"
                  className="transition-all duration-300 hover:bg-blue-50 dark:hover:bg-blue-950"
                  onClick={handleMicrosoftSignIn}
                  disabled={isLoading}
                  type="button"
                >
                  <svg className="mr-2 h-4 w-4" viewBox="0 0 24 24">
                    <path d="M21.5 10.8H13.25V7.91L21.5 7.83V10.8Z" fill="#4CAF50" />
                    <path d="M21.5 16.5H13.25V13.45H21.5V16.5Z" fill="#F44336" />
                    <path d="M13.25 7.83V16.5H9.25V7.83H13.25Z" fill="#2196F3" />
                    <path d="M9.25 16.5H2.5V7.83H9.25V16.5Z" fill="#FFC107" />
                  </svg>
                  Microsoft
                </Button>
              </div>
            </div>
          </CardContent>
          <CardFooter className="flex justify-center">
            <p className="text-sm text-muted-foreground">
              Already have an account?{" "}
              <Link href="/login" className="text-primary hover:underline transition-colors">
                Sign in
              </Link>
            </p>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}

